# display
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

# colours
GREEN = (120, 150, 85)
LIGHT_BEIGE = (235, 235, 205)

# board
TILES = 8
SQ_HEIGHT = SCREEN_HEIGHT//TILES
SQ_WIDTH = SCREEN_WIDTH//TILES
SQ_SIZE = (SQ_WIDTH, SQ_HEIGHT)
EMPTY = '  '